---
runtime: shiny
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, eval=TRUE, message=FALSE, warning=FALSE)
```


```{r, results = 'asis'}
if(input$study_objective == ""){
  cat("<b><center>Please select a study objective.</center></b>")
} else {
  cat("<h4><center> - ODMAP protocol - </center></h4>", sep = "")
  cat("<h2><center>", input$study_title, "</center></h2>", sep = "")
  cat("<p><b>Model objective:</b> ", input$study_objective, "</p>", sep = "")
  cat("<p><b>Authors:</b> ", paste(authors$text, collapse = ", "), "</p>", sep = "")
  cat("<p><b>DOI:</b> ", input$DOI, "</p>", sep = "")
  cat("<p><b>Date:</b> ", as.character(Sys.Date()), "</p>", sep = "")
  cat("\n", "______________", "\n", sep = "")
  
  section = ""
  subsection = ""
  for(i in 1:nrow(elem_input)){
    # Find out if new section header needs to be rendered
    section_new = elem_input$section_id[i]
    if(section_new != section & !(section_new %in% elem_hide[[input$study_objective]])){
      section = section_new
      knit_section(section)
    }
    
    # Find out if new subsection header needs to be rendered
    subsection_new = elem_input$subsection_id[i]
    if(subsection_new != subsection & !(subsection_new %in% elem_hide[[input$study_objective]])){
      subsection = subsection_new
      knit_subsection(subsection)
    }
    
    # Render paragraphs
    paragraph_id = elem_input$paragraph_id[i]
    if (i==1) {
      knit_element_obj(paragraph_id)
    } else
    if(paragraph_id %in% names(input)){
      if(input[[paragraph_id]] == ""){
        cat("<span style='color:#ff4c3f'>")
        knit_element_empty(paragraph_id)
        cat("</span>")
      } else {
        knit_element_text(paragraph_id)
      }
    }
  }
}
```